// <auto-generated />
using System;
using Garage2._0.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Garage2._0.Migrations
{
    [DbContext(typeof(Garage2_0Context))]
    [Migration("20210311103457_SeedDataAdded")]
    partial class SeedDataAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Garage2._0.Models.ParkedVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Brand")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("NrOfWheels")
                        .HasColumnType("int");

                    b.Property<string>("RegNr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ParkedVehicle");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArrivalTime = new DateTime(2020, 12, 25, 8, 15, 30, 0, DateTimeKind.Unspecified),
                            Brand = "Volvo",
                            Color = "Red",
                            Model = "XC40",
                            NrOfWheels = 4,
                            RegNr = "ABC001",
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 2,
                            ArrivalTime = new DateTime(2020, 12, 31, 16, 25, 0, 0, DateTimeKind.Unspecified),
                            Brand = "",
                            Color = "Black",
                            Model = "",
                            NrOfWheels = 4,
                            RegNr = "BCA321",
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 3,
                            ArrivalTime = new DateTime(2021, 3, 10, 21, 10, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Harley Davidson",
                            Color = "Green",
                            Model = "Low rider",
                            NrOfWheels = 2,
                            RegNr = "HDA555",
                            VehicleType = 2
                        },
                        new
                        {
                            Id = 4,
                            ArrivalTime = new DateTime(2021, 3, 9, 22, 15, 8, 480, DateTimeKind.Local).AddTicks(752),
                            Brand = "Volkswagen",
                            Color = "Blue",
                            Model = "Golf",
                            NrOfWheels = 4,
                            RegNr = "MLB11U",
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 5,
                            ArrivalTime = new DateTime(2021, 3, 11, 9, 4, 56, 485, DateTimeKind.Local).AddTicks(4690),
                            Brand = "Scania",
                            Color = "White",
                            Model = "L320",
                            NrOfWheels = 4,
                            RegNr = "SCA777",
                            VehicleType = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
